[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures-util = { version = "0.3", features = ["sink"] }
tokio-tungstenite = "0.26.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"


